copyright = "Original-Theme is licensed with the Creative Commons Attribution 3.0 Unported License"
baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Editorial by HTML5 UP"
theme = "hugo-editorial"
Paginate = 3

DefaultContentLanguage = "pl"
DefaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
	weight = 1
	languageName = "English"
	title = "Ostrowik Observatory"

[[Languages.en.menu.main]]
	url 	= "/en"
	name 	= "Home"
	weight	= 0

[Languages.pl]
	weight = 0
	languageName = "Polish"
	title = "Obserwatorium w Ostrowiku"

[[Languages.pl.menu.main]]
	url 	= "/"
	name 	= "Home"
	weight	= 0


[params]
	fronttitle = "Ostrowik"
	frontsubline = "Stacja Obserwacyjna Obserwatorium Astronomicznego UW"
	frontintro = "."
	learnmore = "Więcej"
	learnmorelink = "/"

[params.contact]
	title 		= "Kontakt"
	intro 		= ""
	email 		= "msitek@astrouw.edu.pl"
	phone 		= "+48 22 789 79 66"
	address 	= "Ostrowik 15"

[params.miniposts]
	title 		= "Aktualności"

[params.nav]
	title 		= "Menu"

[params.showcase]
	title		= "Erat lacinia"
	icon1		= "fa-diamond"
	headline1	= "Portitor ullamcorper"
	intro1		= "Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam."
	icon2		= "fa-paper-plane"
	headline2	= "Sapien veroeros"
	intro2		= "Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam."
	icon3		= "fa-rocket"
	headline3	= "Quam lorem ipsum"
	intro3		= "Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam."
	icon4		= "fa-signal"
	headline4	= "Sed magna finibus"
	intro4		= "Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam."
	title2 		= "Ipsum sed dolor"


[[menu.main]]
 	name = "home"
	url = "/"
	weight = -200
